# Generated by Django 3.1.7 on 2021-03-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='week',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
