# Generated by Django 3.1.7 on 2021-03-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0003_auto_20210329_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
