# Generated by Django 3.1.7 on 2021-03-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0007_task_type_of_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type_of_task',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='TypesOfTasks',
        ),
    ]
