# Generated by Django 3.1.7 on 2021-03-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0008_auto_20210331_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type_of_task',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
