# Generated by Django 3.1.7 on 2021-04-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0009_auto_20210331_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
