# Generated by Django 3.1.7 on 2021-04-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0010_task_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='answer',
        ),
    ]
