# Generated by Django 3.1.7 on 2021-04-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0011_remove_task_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batches',
            name='coordinator',
        ),
        migrations.CreateModel(
            name='BatchSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.batches')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.week')),
            ],
        ),
    ]
