# Generated by Django 3.1.7 on 2021-04-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0013_auto_20210416_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='batch',
        ),
    ]
