# Generated by Django 3.1.7 on 2021-04-19 06:52

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0014_remove_task_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='green')),
                ('yellow', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='yellow')),
                ('orange', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='orange')),
                ('red', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='red')),
            ],
        ),
    ]
