# Generated by Django 3.1.7 on 2021-04-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0015_reviewcolors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewColors',
        ),
    ]
