# Generated by Django 3.1.7 on 2021-04-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0018_auto_20210419_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewcolors',
            old_name='name',
            new_name='description',
        ),
    ]
