# Generated by Django 3.1.7 on 2021-04-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0020_auto_20210420_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatordetails',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
