# Generated by Django 3.1.7 on 2021-03-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_cautiondeposit_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cautiondeposit',
            name='coordinator',
        ),
        migrations.AddField(
            model_name='student',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
