# Generated by Django 3.1.7 on 2021-03-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20210325_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='is_verify',
        ),
        migrations.AddField(
            model_name='student',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
