# Generated by Django 3.1.7 on 2021-03-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210325_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_verify',
            new_name='email_verfied',
        ),
    ]
