# Generated by Django 3.1.7 on 2021-03-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_invalidresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admin_approval',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
