# Generated by Django 3.1.7 on 2021-03-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_studentuuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuuid',
            old_name='uuid',
            new_name='student_uuid',
        ),
    ]
