# Generated by Django 3.1.7 on 2021-03-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20210327_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuuid',
            name='student_uuid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
