# Generated by Django 3.1.7 on 2021-03-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20210328_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuuid',
            name='student_uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
