# Generated by Django 3.1.7 on 2021-04-19 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0014_remove_task_batch'),
        ('student', '0027_answer_coordintator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='coordintator',
        ),
        migrations.CreateModel(
            name='AnswerEdited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinator.coordinatordetails')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
